### ISSUE TITLE
Nextcloud Server is not responding while trying to download or open files using GONextcloud API

### ISSUE THREAD

**Issue by chhelsingh** [partitio/gonextcloud#1]
I was trying to download files from the Nextcloud server through Gonextcloud API, but getting some errors of nextcloud server not responding . Nextcloud server is responding sometimes but not all the time.
![image](https://user-images.githubusercontent.com/50014456/65035425-c5cdc800-d966-11e9-8abf-381c8b1439c6.png)

As you can see in the left down corner Photos.zip is downloaded but the next time I try to download again it fails to do so.

![image](https://user-images.githubusercontent.com/50014456/65035458-ded67900-d966-11e9-9fb2-097adcece42d.png)

![image](https://user-images.githubusercontent.com/50014456/65035467-e6961d80-d966-11e9-96c4-a55888282af5.png)

Why is this happening?

**Comment by Adphi** [comment]
I am sorry for the late answer, I have not been notified by your issue creation at the time.
It seems you may have configuration issues with your Nextcloud instance. There is not much I can do without logs.
