### ISSUE TITLE
Error 405 Method not allowed occurs when I try to read directories from my Nexcloud account using Gonextcloud API

### ISSUE THREAD

**Issue by aggarwalanubhav** [partitio/gonextcloud#2]
@Adphi ,The function ReadDir displays the following error.
![ReadDir error1](https://user-images.githubusercontent.com/45697893/72778926-5a5f7400-3c40-11ea-8a11-3f4c642a61a3.PNG)

`func Authentication() gonextcloud.Client {
	client, err := gonextcloud.NewClient(gsURL) // Creating and login user on Nextcloud
	if err != nil {
		panic(err)
	}
	if err := client.Login(gsUsername, gsPassword); err != nil {
        panic(err)
    }
    defer client.Logout() 
	return client
}

// ListDirectory : List the Directories/Files
func ListDirectory(client gonextcloud.Client) []os.FileInfo {
	folders, err := client.WebDav().ReadDir(".") //  "//"- for Root  Directory listing   " Folder name" - folder listing
	fmt.Println("Unable to list files: ", err)
	for n, file := range folders {
		if file.IsDir() {
			fmt.Println(n, ".  Dir ", " "+file.Name())
		} else {
			fmt.Println(n, ".  File", " "+file.Name())
		}
	}
	return folders
}`

The package imported is "github.com/partitio/gonextcloud". The package "gitlab.bertha.cloud/partitio/Nextcloud-Partitio/gonextcloud" has also been tried but the same error arises.

Calling of the functions is done in the following way:
`client := nextcloud.Authentication() //Create and login client
directories := nextcloud.ListDirectory(client) //To retrieve and print the list of files and folders`

Please reply ASAP, very urgent!

**Comment by Adphi** [comment]
Hello,
I can see some problems in your code example :
```golang
func Authentication() gonextcloud.Client {
	client, err := gonextcloud.NewClient(gsURL) // Creating and login user on Nextcloud
	if err != nil {
		panic(err)
	}
	if err := client.Login(gsUsername, gsPassword); err != nil {
		panic(err)
	}
	defer client.Logout() // <== the client is logout as soon as the Authenticate method ends ...
	return client
}

// ListDirectory : List the Directories/Files
func ListDirectory(client gonextcloud.Client) []os.FileInfo {
	folders, err := client.WebDav().ReadDir(".") // "//"- for Root Directory listing " Folder name" - folder listing
	fmt.Println("Unable to list files: ", err)
	for n, file := range folders {
		if file.IsDir() {
			fmt.Println(n, ". Dir ", " "+file.Name())
		} else {
			fmt.Println(n, ". File", " "+file.Name())
		}
	}
	return folders
}

func main() {
	c := Authentication()
	ListDirectory(c) // <= the client is logged out ...
}
```

Which Nextcloud version are your using ?
Also, try using `client.WebDav().ReadDir("/")` instead of `client.WebDav().ReadDir(".")`.

**Comment by aggarwalanubhav** [comment]
> Hello,
> I can see some problems in your code example :
> 
> ```go
> func Authentication() gonextcloud.Client {
> 	client, err := gonextcloud.NewClient(gsURL) // Creating and login user on Nextcloud
> 	if err != nil {
> 		panic(err)
> 	}
> 	if err := client.Login(gsUsername, gsPassword); err != nil {
> 		panic(err)
> 	}
> 	defer client.Logout() // <== the client is logout as soon as the Authenticate method ends ...
> 	return client
> }
> 
> // ListDirectory : List the Directories/Files
> func ListDirectory(client gonextcloud.Client) []os.FileInfo {
> 	folders, err := client.WebDav().ReadDir(".") // "//"- for Root Directory listing " Folder name" - folder listing
> 	fmt.Println("Unable to list files: ", err)
> 	for n, file := range folders {
> 		if file.IsDir() {
> 			fmt.Println(n, ". Dir ", " "+file.Name())
> 		} else {
> 			fmt.Println(n, ". File", " "+file.Name())
> 		}
> 	}
> 	return folders
> }
> 
> func main() {
> 	c := Authentication()
> 	ListDirectory(c) // <= the client is logged out ...
> }
> ```
> 
> Which Nextcloud version are your using ?
> Also, try using `client.WebDav().ReadDir("/")` instead of `client.WebDav().ReadDir(".")`.

I tried using client.WebDav().ReadDir("/") as you suggested, but it also gives the same error. And I've just created an account on QloudData powered by Nextcloud, does the version matter in that case?

**Comment by Adphi** [comment]
I did not test gonextloud against v17 and v18.
gonextcloud use [gowebdav](https://github.com/studio-b12/gowebdav) for the webdav part, you could try directly using it :
```golang
package main

import (
	"fmt"

	"github.com/studio-b12/gowebdav"
)

const (
        gsURL = "https://my.nextcloud.com"
        gsUsername = "user"
        gsPassword = "password"
)

func main() {
	root := gsURL + "/remote.php/webdav"

	c := gowebdav.NewClient(root, gsUsername, gsPassword)
	fs, err := c.ReadDir("/")
	if err != nil {
		panic(err)
	}
	for _, f := range fs {
		fmt.Println(f)
	}
}

```

**Comment by aggarwalanubhav** [comment]
> I did not test gonextloud against v17 and v18.
> gonextcloud use [gowebdav](https://github.com/studio-b12/gowebdav) for the webdav part, you could try directly using it :
> 
> ```go
> package main
> 
> import (
> 	"fmt"
> 
> 	"github.com/studio-b12/gowebdav"
> )
> 
> const (
>         gsURL = "https://my.nextcloud.com"
>         gsUsername = "user"
>         gsPassword = "password"
> )
> 
> func main() {
> 	root := gsURL + "/remote.php/webdav"
> 
> 	c := gowebdav.NewClient(root, gsUsername, gsPassword)
> 	fs, err := c.ReadDir("/")
> 	if err != nil {
> 		panic(err)
> 	}
> 	for _, f := range fs {
> 		fmt.Println(f)
> 	}
> }
> ```

My gsURL is https://cloud.owncube.com/login. Would your code run for the same as well?

**Comment by Adphi** [comment]
your gsURL must be https://cloud.owncube.com, not https://cloud.owncube.com/login

**Comment by aggarwalanubhav** [comment]
> your gsURL must be https://cloud.owncube.com, not https://cloud.owncube.com/login

Thanks, sir. It worked.

**Comment by aggarwalanubhav** [comment]
> > I did not test gonextloud against v17 and v18.
> > gonextcloud use [gowebdav](https://github.com/studio-b12/gowebdav) for the webdav part, you could try directly using it :
> > ```go
> > package main
> > 
> > import (
> > 	"fmt"
> > 
> > 	"github.com/studio-b12/gowebdav"
> > )
> > 
> > const (
> >         gsURL = "https://my.nextcloud.com"
> >         gsUsername = "user"
> >         gsPassword = "password"
> > )
> > 
> > func main() {
> > 	root := gsURL + "/remote.php/webdav"
> > 
> > 	c := gowebdav.NewClient(root, gsUsername, gsPassword)
> > 	fs, err := c.ReadDir("/")
> > 	if err != nil {
> > 		panic(err)
> > 	}
> > 	for _, f := range fs {
> > 		fmt.Println(f)
> > 	}
> > }
> > ```
> 
> My gsURL is https://cloud.owncube.com/login. Would your code run for the same as well?



> I did not test gonextloud against v17 and v18.
> gonextcloud use [gowebdav](https://github.com/studio-b12/gowebdav) for the webdav part, you could try directly using it :
> 
> ```go
> package main
> 
> import (
> 	"fmt"
> 
> 	"github.com/studio-b12/gowebdav"
> )
> 
> const (
>         gsURL = "https://my.nextcloud.com"
>         gsUsername = "user"
>         gsPassword = "password"
> )
> 
> func main() {
> 	root := gsURL + "/remote.php/webdav"
> 
> 	c := gowebdav.NewClient(root, gsUsername, gsPassword)
> 	fs, err := c.ReadDir("/")
> 	if err != nil {
> 		panic(err)
> 	}
> 	for _, f := range fs {
> 		fmt.Println(f)
> 	}
> }
> ```

One more question. What would gowebdav.NewClient(root, gsUsername, gsPassword) return if the credentials are incorrect?

**Comment by Adphi** [comment]
It will throw a 401 Unauthorized error: `Authorize https://my.nextcloud.com/remote.php/webdav/: 401`

**Comment by aggarwalanubhav** [comment]
> It will throw a 401 Unauthorized error: `Authorize https://my.nextcloud.com/remote.php/webdav/: 401`

Thanks. Also, could you please help me as to what should be my complete link/path with reference to mt login path to download a particular file in my account?

**Comment by Adphi** [comment]
I am sorry I don't understand your question.

**Comment by aggarwalanubhav** [comment]
> I am sorry I don't understand your question.

Well, I want to download files from my account, 

webdavFilePath := "folder/subfolder/file.txt"
localFilePath := "/tmp/webdav/file.txt"

reader, _ := c.ReadStream(webdavFilePath)

file, _ := os.Create(localFilePath)
defer file.Close()

io.Copy(file, reader)

as in this function in gowebdav. 
So, what I want to ask is, what should my webdavFilePath?

**Comment by Adphi** [comment]
You create the client with your root url `https://cloud.owncube.com`, then the paths are relative to the root of your nextcloud account.
So if you have `/folder/subfolder/file.txt` it should be `folder/subfolder/file.txt`

**Comment by aggarwalanubhav** [comment]
> You create the client with your root url `https://cloud.owncube.com`, then the paths are relative to the root of your nextcloud account.
> So if you have `/folder/subfolder/file.txt` it should be `folder/subfolder/file.txt`

And what if I want to download all the files, maintaining the file structure as in the account. How can I do that?

**Comment by Adphi** [comment]
Use gonextcloud's Walk method.
Asynchronous example:
```golang
package main

import (
	"fmt"
	"io"
	"os"
	"path/filepath"

	"gitlab.bertha.cloud/partitio/Nextcloud-Partitio/gonextcloud"
)

const (
        gsURL = "https://my.nextcloud.com"
        gsUsername = "user"
        gsPassword = "password"
)

func main() {
	c, err := gonextcloud.NewClient(gsURL)
	if err != nil {
		panic(err)
	}
	if err := c.Login(gsUsername, gsPassword); err != nil {
		panic(err)
	}
	defer c.Logout()
	dst := filepath.Join(os.TempDir(), "webdav")
	fmt.Println("copying webdav data in", dst)
	err = c.WebDav().Walk("/", func(path string, info os.FileInfo, err error) error {
		go func() {
			if info.IsDir() {
				dstPath := filepath.Join(dst, path)
				fmt.Println("creating directory", dstPath)
				if err := os.MkdirAll(dstPath, os.ModePerm); err != nil {
					panic(err)
				}
				return
			}
			s, err := c.WebDav().ReadStream(path)
			if err != nil {
				panic(err)
			}
			defer s.Close()
			dstPath := filepath.Join(dst, path)
			fmt.Println("copying file", dstPath)
			out, err := os.Create(dstPath)
			if err != nil {
				panic(err)
			}
			defer out.Close()
			if _, err := io.Copy(out, s); err != nil {
				panic(err)
			}
		}()
		return nil
	})
	if err != nil {
		panic(err)
	}
}

```

**Comment by aggarwalanubhav** [comment]
> Use gonextcloud's Walk method.
> Asynchronous example:
> 
> ```go
> package main
> 
> import (
> 	"fmt"
> 	"io"
> 	"os"
> 	"path/filepath"
> 
> 	"gitlab.bertha.cloud/partitio/Nextcloud-Partitio/gonextcloud"
> )
> 
> const (
>         gsURL = "https://my.nextcloud.com"
>         gsUsername = "user"
>         gsPassword = "password"
> )
> 
> func main() {
> 	c, err := gonextcloud.NewClient(gsURL)
> 	if err != nil {
> 		panic(err)
> 	}
> 	if err := c.Login(gsUsername, gsPassword); err != nil {
> 		panic(err)
> 	}
> 	defer c.Logout()
> 	dst := filepath.Join(os.TempDir(), "webdav")
> 	fmt.Println("copying webdav data in", dst)
> 	err = c.WebDav().Walk("/", func(path string, info os.FileInfo, err error) error {
> 		go func() {
> 			if info.IsDir() {
> 				dstPath := filepath.Join(dst, path)
> 				fmt.Println("creating directory", dstPath)
> 				if err := os.MkdirAll(dstPath, os.ModePerm); err != nil {
> 					panic(err)
> 				}
> 				return
> 			}
> 			s, err := c.WebDav().ReadStream(path)
> 			if err != nil {
> 				panic(err)
> 			}
> 			defer s.Close()
> 			dstPath := filepath.Join(dst, path)
> 			fmt.Println("copying file", dstPath)
> 			out, err := os.Create(dstPath)
> 			if err != nil {
> 				panic(err)
> 			}
> 			defer out.Close()
> 			if _, err := io.Copy(out, s); err != nil {
> 				panic(err)
> 			}
> 		}()
> 		return nil
> 	})
> 	if err != nil {
> 		panic(err)
> 	}
> }
> ```

 But I'll have to use the gowebdev client, right? This won't work for the same.

**Comment by Adphi** [comment]
The solution to your problem is :
> your gsURL must be https://cloud.owncube.com, not https://cloud.owncube.com/login

The method Walk is inside `gonextcloud`, it does not exist in `gowebdav`.
The example code should work with your nextcloud instance using its root url https://cloud.owncube.com.

**Comment by aggarwalanubhav** [comment]
> Use gonextcloud's Walk method.
> Asynchronous example:
> 
> ```go
> package main
> 
> import (
> 	"fmt"
> 	"io"
> 	"os"
> 	"path/filepath"
> 
> 	"gitlab.bertha.cloud/partitio/Nextcloud-Partitio/gonextcloud"
> )
> 
> const (
>         gsURL = "https://my.nextcloud.com"
>         gsUsername = "user"
>         gsPassword = "password"
> )
> 
> func main() {
> 	c, err := gonextcloud.NewClient(gsURL)
> 	if err != nil {
> 		panic(err)
> 	}
> 	if err := c.Login(gsUsername, gsPassword); err != nil {
> 		panic(err)
> 	}
> 	defer c.Logout()
> 	dst := filepath.Join(os.TempDir(), "webdav")
> 	fmt.Println("copying webdav data in", dst)
> 	err = c.WebDav().Walk("/", func(path string, info os.FileInfo, err error) error {
> 		go func() {
> 			if info.IsDir() {
> 				dstPath := filepath.Join(dst, path)
> 				fmt.Println("creating directory", dstPath)
> 				if err := os.MkdirAll(dstPath, os.ModePerm); err != nil {
> 					panic(err)
> 				}
> 				return
> 			}
> 			s, err := c.WebDav().ReadStream(path)
> 			if err != nil {
> 				panic(err)
> 			}
> 			defer s.Close()
> 			dstPath := filepath.Join(dst, path)
> 			fmt.Println("copying file", dstPath)
> 			out, err := os.Create(dstPath)
> 			if err != nil {
> 				panic(err)
> 			}
> 			defer out.Close()
> 			if _, err := io.Copy(out, s); err != nil {
> 				panic(err)
> 			}
> 		}()
> 		return nil
> 	})
> 	if err != nil {
> 		panic(err)
> 	}
> }
> ```

Ok. Also, what do filepath and dst refer to in the above code?

**Comment by Adphi** [comment]
dst is the destination directory.
filepath is a Go package from the standard library, it help handling file paths..
