### ISSUE TITLE
What is the use and need of ReadStream function?

### ISSUE THREAD

**Issue by aggarwalanubhav** [partitio/gonextcloud#3]
Hello @Adphi , may I please know what is the use and need of this ReadDir function defined in "vendor/gitlab.bertha.cloud/adphi/gowebdav/client.go"?

The function code goes like following:
`
func (c *Client) ReadStream(path string) (io.ReadCloser, error) {
	rs, err := c.req("GET", path, nil, nil)
	if err != nil {
		return nil, newPathErrorErr("ReadStream", path, err)
	}

	if rs.StatusCode == 200 {
		return rs.Body, nil
	}

	rs.Body.Close()
	return nil, newPathError("ReadStream", path, rs.StatusCode)
}
`
Urgent!

**Comment by Adphi** [comment]
The packages in vendor are dependencies. gitlab.bertha.cloud/adphi/gowebdav is a fork from [gowebdav](https://github.com/studio-b12/gowebdav), if you have any question please create an issue [there](https://github.com/studio-b12/gowebdav/issues).
